import img1 from "../assets/download.jpg";
import img2 from "../assets/experience.jpg";
import img3 from "../assets/download (3).jpg";
import img4 from "../assets/download (4).jpg";
import img5 from "../assets/download (5).jpg";
import img6 from "../assets/images.jpg";
import img7 from "../assets/download (6).jpg";
import img8 from "../assets/ph_tech.jpg";
import img9 from "../assets/Oil and Gas.jpg";
import img10 from "../assets/enugu.jpg";
import img11 from "../assets/lagos.jpg";

export const states = ["Nigeria", "Lagos", "Abuja", "Rivers", "Enugu", "Abia"];

export const events = [
  {
    title: "Lagos Tech Fest 2026",
    type: "Tech",
    state: "Lagos",
    date: "Feb 18",
    venue: "Landmark Centre",
    price: "₦25,000",
    img: "https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=1000",
    status: "Trending",
  },
  {
    title: "Africa Technology Expo",
    type: "Tech",
    state: "Lagos",
    date: "Jun 26",
    venue: "Landmark Centre",
    price: "Free",
    img: img1,
    status: "Global",
  },
  {
    title: "Social Media Week Lagos",
    type: "Tech",
    state: "Lagos",
    date: "Mar 04",
    venue: "Landmark Centre",
    price: "₦15,000",
    img: img11,
    status: "Popular",
  },
  {
    title: "Lagos Fashion Week",
    type: "Culture",
    state: "Lagos",
    date: "Oct 22",
    venue: "Federal Palace Hotel",
    price: "₦10,000",
    img: "https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000",
    status: "Cultural",
  },
  {
    title: "Gidi Culture Fest",
    type: "Music",
    state: "Lagos",
    date: "Apr 11",
    venue: "Hard Rock Cafe",
    price: "₦20,000",
    img: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1000",
    status: "Festive",
  },
  {
    title: "Art X Lagos",
    type: "Culture",
    state: "Lagos",
    date: "Nov 02",
    venue: "Civic Centre",
    price: "₦5,000",
    img: img6,
    status: "Arts",
  },
  {
    title: "Lagos International Trade Fair",
    type: "Business",
    state: "Lagos",
    date: "Nov 07",
    venue: "Tafawa Balewa Square",
    price: "₦500",
    img: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=1000",
    status: "Business",
  },
  {
    title: "The Experience Lagos",
    type: "Music",
    state: "Lagos",
    date: "Dec 04",
    venue: "TBS Square",
    price: "Free",
    img: img2,
    status: "Spiritual",
  },
  {
    title: "Lagos Book & Art Festival",
    type: "Culture",
    state: "Lagos",
    date: "Nov 14",
    venue: "Freedom Park",
    price: "Free",
    img: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?q=80&w=1000",
    status: "Literary",
  },
  {
    title: "Flytime Music Festival",
    type: "Music",
    state: "Lagos",
    date: "Dec 21",
    venue: "Eko Hotels",
    price: "₦35,000",
    img: "https://images.unsplash.com/photo-1493225255756-d9584f8606e9?q=80&w=1000",
    status: "Concert",
  },
  {
    title: "GITEX Nigeria 2026",
    type: "Tech",
    state: "Abuja",
    date: "Sept 07",
    venue: "Falcon Square",
    price: "₦50,000",
    img: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=1000",
    status: "Massive",
  },
  {
    title: "Abuja International Carnival",
    type: "Culture",
    state: "Abuja",
    date: "Nov 25",
    venue: "Eagle Square",
    price: "Free",
    img: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?q=80&w=1000",
    status: "National",
  },
  {
    title: "NICON Business Summit",
    type: "Business",
    state: "Abuja",
    date: "May 14",
    venue: "NICON Luxury",
    price: "₦40,000",
    img: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=80&w=1000",
    status: "Executive",
  },
  {
    title: "Abuja Tech Week",
    type: "Tech",
    state: "Abuja",
    date: "Oct 12",
    venue: "ICCA",
    price: "₦10,000",
    img: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=1000",
    status: "Innovation",
  },
  {
    title: "Central Bank Policy Forum",
    type: "Business",
    state: "Abuja",
    date: "Mar 18",
    venue: "CBN HQ",
    price: "Invite",
    img: "https://images.unsplash.com/photo-1554224155-1696413565d3?q=80&w=1000",
    status: "Financial",
  },
  {
    title: "Aba Trade Fair 2026",
    type: "Business",
    state: "Abia",
    date: "Nov 12",
    venue: "Aba Mega Mall",
    price: "Free",
    img: img3,
    status: "Major Trade",
  },
  {
    title: "Enterprise Summit Aba",
    type: "Business",
    state: "Abia",
    date: "Mar 26",
    venue: "Astro Halls",
    price: "Free",
    img: "https://images.unsplash.com/photo-1556761175-b413da4baf72?q=80&w=1000",
    status: "Free",
  },
  {
    title: "Ekpe Cultural Festival",
    type: "Culture",
    state: "Abia",
    date: "Dec 28",
    venue: "Arochukwu",
    price: "Free",
    img: img4,
    status: "Ancestral",
  },
  {
    title: "Umuahia Tech Meetup",
    type: "Tech",
    state: "Abia",
    date: "Apr 05",
    venue: "Michael Okpara Uni",
    price: "₦2,000",
    img: img5,
    status: "Community",
  },
  {
    title: "Art Experience Aba",
    type: "Music",
    state: "Abia",
    date: "Dec 14",
    venue: "Oris Lounge",
    price: "₦5,000",
    img: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1000",
    status: "Nightlife",
  },
  {
    title: "Enugu Tech Festival",
    type: "Tech",
    state: "Enugu",
    date: "Feb 23",
    venue: "ICC Enugu",
    price: "Free",
    img: img10,
    status: "Coal to Code",
  },
  {
    title: "Road Block Music Concert",
    type: "Music",
    state: "Enugu",
    date: "Dec 20",
    venue: "Michael Okpara Square",
    price: "₦3,000",
    img: img7,
    status: "Homecoming",
  },
  {
    title: "Funky 4 Gang Concert",
    type: "Music",
    state: "Enugu",
    date: "Feb 22",
    venue: "Amadeo Centre",
    price: "₦5,000",
    img: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=1000",
    status: "Vibes",
  },
  {
    title: "Enugu Business Expo",
    type: "Business",
    state: "Enugu",
    date: "Aug 15",
    venue: "Polo Park Mall",
    price: "Free",
    img: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1000",
    status: "SME Focus",
  },
  {
    title: "Coal City Film Fest",
    type: "Culture",
    state: "Enugu",
    date: "Mar 20",
    venue: "Enugu National Museum",
    price: "₦2,000",
    img: "https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=1000",
    status: "Cinema",
  },
  {
    title: "TechUp Port Harcourt",
    type: "Tech",
    state: "Rivers",
    date: "May 22",
    venue: "Harvoxx Hub",
    price: "Free",
    img: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?q=80&w=1000",
    status: "Big Tech",
  },
  {
    title: "PH Tech Vibes",
    type: "Tech",
    state: "Rivers",
    date: "Feb 21",
    venue: "Barachiel Place",
    price: "Free",
    img: img8,
    status: "Networking",
  },
  {
    title: "Carniriv",
    type: "Culture",
    state: "Rivers",
    date: "Dec 15",
    venue: "PH Liberation Stadium",
    price: "Free",
    img: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?q=80&w=1000",
    status: "Massive",
  },
  {
    title: "Oil & Gas Expo",
    type: "Business",
    state: "Rivers",
    date: "Jul 10",
    venue: "Hotel Presidential",
    price: "₦100,000",
    img: img9,
    status: "Global",
  },
  {
    title: "Garden City Music Fest",
    type: "Music",
    state: "Rivers",
    date: "Nov 30",
    venue: "Polo Club PH",
    price: "₦15,000",
    img: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=1000",
    status: "Premium",
  },
];

export default events;
